#!/usr/bin/env node --experimental-strip-types
/**
 * RULES.md, generated.
 *
 * One page listing every shipped rule, from the rules themselves: what each
 * asks, how it is configured, what proves it and how well. Nothing here is
 * written by hand -- the numbers are `jev-lint eval --replay`'s, re-derived
 * from each rule's accepted baseline -- so the page cannot drift from the
 * rules the way a hand-kept list does. The test suite regenerates it and
 * fails when the committed copy differs.
 *
 *   node --experimental-strip-types tools/rules-md.ts           # write RULES.md
 *   node --experimental-strip-types tools/rules-md.ts --check   # exit 1 if RULES.md is stale
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { discoverEvals, loadSuite, readEvalRecord, scoreEval } from "../src/evals.ts";
import { loadRules } from "../src/rules.ts";
import { TIER_ONE } from "../src/types.ts";
import type { Rule } from "../src/types.ts";

interface Row {
  rule: Rule;
  dir: string;
  fixtures: number;
  defects: number;
  cleans: number;
  /** From the accepted baseline; null when the rule has none. */
  score: { precision: number | null; recall: number | null; tp: number; fp: number; fn: number; flips: number; passes: number; recorded: string } | null;
}

/** Every shipped rule with what proves it, in language-then-id order. */
export function collectRows(rulesRoot: string): Row[] {
  const { rules, errors } = loadRules([rulesRoot]);
  if (errors.length) throw new Error(errors.join("\n"));
  const suites = new Map(discoverEvals([rulesRoot]).map((s) => [s.dir, s]));
  return rules
    .filter((r) => r.languageDir)
    .sort((a, b) => a.languageDir!.localeCompare(b.languageDir!) || a.id.localeCompare(b.id))
    .map((rule) => {
      const dir = join(rulesRoot, rule.languageDir!, rule.id);
      const suite = suites.get(dir);
      let defects = 0;
      let cleans = 0;
      let score: Row["score"] = null;
      if (suite) {
        const { labels } = loadSuite(suite);
        for (const [k, v] of Object.entries(labels)) {
          if (k.startsWith("$") || !Array.isArray(v)) continue;
          defects += v.filter((l) => l.label === "bad").length;
          cleans += v.filter((l) => l.label === "clean").length;
        }
        const baseline = readEvalRecord(suite.baseline, suite);
        if (baseline) {
          const s = scoreEval(baseline.passes, labels, [rule]).rules.find((x) => x.rule === rule.id);
          if (s) {
            score = {
              precision: s.precision,
              recall: s.recall,
              tp: s.tp,
              fp: s.fp,
              fn: s.fn,
              flips: s.flips,
              passes: baseline.passes.length,
              recorded: baseline.recorded.slice(0, 10),
            };
          }
        }
      }
      return { rule, dir, fixtures: countFixtures(join(dir, "fixtures")), defects, cleans, score };
    });
}

/** Files under fixtures/, or for a commit rule its case directories. */
function countFixtures(dir: string): number {
  if (!existsSync(dir)) return 0;
  let n = 0;
  const walk = (d: string, depth: number) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) {
        // A commit case is a directory holding `message`: one fixture.
        if (existsSync(join(p, "message"))) n += 1;
        else walk(p, depth + 1);
      } else if (e.isFile()) n += 1;
    }
  };
  walk(dir, 0);
  return n;
}

const fmt = (n: number | null): string => (n === null ? "—" : n.toFixed(2));
const oneLine = (s: string): string => s.replace(/\s+/g, " ").trim();

/** `rulesRoot` relative to the cwd, which must be the repository root: baselines record paths that way. */
export function renderRulesMd(rulesRoot: string, repoRoot: string): string {
  const rows = collectRows(rulesRoot);
  const languages = [...new Set(rows.map((r) => r.rule.languageDir!))];
  const ids = [...new Set(rows.map((r) => r.rule.id))].sort();
  const perfect = rows.filter((r) => r.score && r.score.precision === 1 && r.score.recall === 1).length;
  const defects = rows.reduce((a, r) => a + r.defects, 0);
  const out: string[] = [];
  out.push("# Shipped rules");
  out.push("");
  out.push("<!-- Generated by tools/rules-md.ts from rules/. Do not edit; run `npm run rules:md`. -->");
  out.push("");
  out.push(
    `${rows.length} rules under \`rules/<language>/<id>/\`, across ${languages.length} language directories: ` +
      languages.map((l) => `\`${l}\` (${rows.filter((r) => r.rule.languageDir === l).length})`).join(", ") +
      `. First tier: ${TIER_ONE.map((t) => `\`${t}\``).join(", ")}. ` +
      `${perfect} of ${rows.length} reach precision and recall 1.00 at their shipped cutoffs on their own fixtures ` +
      `(${defects} labelled defects in all; \`jev-lint eval --replay\` re-derives every number below from the accepted baselines).`,
  );
  out.push("");
  out.push("## By family");
  out.push("");
  out.push("The cutoff (`threshold`) where the rule exists in that language; blank where it does not.");
  out.push("");
  out.push(`| rule | ${languages.join(" | ")} |`);
  out.push(`| --- | ${languages.map(() => "---").join(" | ")} |`);
  for (const id of ids) {
    const cells = languages.map((l) => {
      const r = rows.find((x) => x.rule.id === id && x.rule.languageDir === l);
      return r ? fmt(r.rule.at) : "";
    });
    out.push(`| \`${id}\` | ${cells.join(" | ")} |`);
  }
  out.push("");
  for (const lang of languages) {
    const mine = rows.filter((r) => r.rule.languageDir === lang);
    out.push(`## ${lang} (${mine.length})`);
    out.push("");
    for (const r of mine) {
      const rule = r.rule;
      out.push(`### \`${lang}/${rule.id}\``);
      out.push("");
      out.push(`> ${oneLine(rule.ask)}`);
      out.push("");
      const bits = [
        `kind \`${rule.kind}\``,
        `subject \`${rule.subject}\``,
        `state \`${rule.state}\``,
        `threshold ${fmt(rule.at)}`,
        ...(rule.loose !== null ? [`loose ${fmt(rule.loose)}`] : []),
        `severity \`${rule.severity}\``,
        `languages ${rule.languages.join(", ")}`,
        ...(rule.explain ? [`explain ${Object.keys(rule.explain).join(" / ")}`] : []),
        ...(rule.split ? [`split \`${rule.split}\``] : []),
        ...(rule.extensions ? [`extensions ${rule.extensions.join(", ")}`] : []),
      ];
      out.push(`- ${bits.join(" · ")}`);
      const proof = r.score
        ? `${r.fixtures} fixture${r.fixtures === 1 ? "" : "s"}, ${r.defects} defect${r.defects === 1 ? "" : "s"}, ${r.cleans} labelled clean${r.cleans === 1 ? "" : "s"}; ` +
          `at the shipped cutoff P ${fmt(r.score.precision)} R ${fmt(r.score.recall)} (tp ${r.score.tp}, fp ${r.score.fp}, fn ${r.score.fn}), ` +
          `${r.score.flips} flip${r.score.flips === 1 ? "" : "s"} over ${r.score.passes} pass${r.score.passes === 1 ? "" : "es"}, baseline ${r.score.recorded}`
        : `${r.fixtures} fixture${r.fixtures === 1 ? "" : "s"}, ${r.defects} defect${r.defects === 1 ? "" : "s"}; **uncalibrated** (no accepted baseline)`;
      out.push(`- ${proof}`);
      out.push(`- [\`${relative(repoRoot, r.dir)}/rule.yml\`](${relative(repoRoot, r.dir)}/rule.yml)`);
      out.push("");
    }
  }
  return `${out.join("\n").trimEnd()}\n`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const repoRoot = resolve(fileURLToPath(import.meta.url), "..", "..");
  // Baselines record fixture paths relative to the repository root, as a
  // run reports them, so the rules root has to be named the same way.
  process.chdir(repoRoot);
  const target = join(repoRoot, "RULES.md");
  const text = renderRulesMd("rules", repoRoot);
  if (process.argv.includes("--check")) {
    const current = existsSync(target) ? readFileSync(target, "utf8") : "";
    if (current !== text) {
      process.stderr.write("RULES.md is stale: run `npm run rules:md` and commit the result\n");
      process.exit(1);
    }
    process.stdout.write("RULES.md is up to date\n");
  } else {
    writeFileSync(target, text);
    process.stdout.write(`wrote ${target} (${statSync(target).size} bytes)\n`);
  }
}
